# Generated by Django 5.1.7 on 2025-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessorio',
            name='nome',
        ),
    ]
