# Generated by Django 5.1.7 on 2025-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Acessorio',
            name='nome',
            
        ),
    ]
