# Generated by Django 5.1.7 on 2025-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_acessorio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
