# Generated by Django 5.1.7 on 2025-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
    ]
