# Generated by Django 5.1.7 on 2025-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_veiculo_cor_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(blank=True, related_name='veiculo', to='core.acessorio'),
        ),
    ]
